channels:
  - conda-forge
dependencies:
  - python=3.12
  - lumispy=0.3.0
  - hyperspy-base=2.4.0
  - exspy=0.3.2
  - rosettasciio-base=0.12.0
  - hyperspy-gui-ipywidgets=2.1.0
  - ipympl=0.10.0
  - scikit-learn=1.8.0
  - numba=0.64.0
  - pyxem==0.21.0
